/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#004f54",
        "on-surface-variant": "#42474f",
        "inverse-on-surface": "#ebf1ff",
        "outline": "#727780",
        "tertiary-fixed": "#e0e3e5",
        "secondary-fixed-dim": "#70d6df",
        "background": "#f9f9ff",
        "outline-variant": "#c2c7d1",
        "on-tertiary-fixed-variant": "#434749",
        "secondary-fixed": "#8df2fc",
        "on-tertiary-fixed": "#181c1e",
        "on-surface": "#111c2c",
        "on-primary-fixed": "#001c37",
        "on-secondary-fixed": "#002022",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dee8ff",
        "primary-fixed-dim": "#a0c9ff",
        "surface-container": "#e7eeff",
        "secondary": "#006970",
        "on-background": "#111c2c",
        "error": "#ba1a1a",
        "primary-fixed": "#d2e4ff",
        "on-primary-container": "#8ebdf9",
        "on-error": "#ffffff",
        "primary-container": "#0f4c81",
        "primary": "#00355f",
        "surface-container-low": "#f0f3ff",
        "surface-dim": "#cfdaf1",
        "inverse-surface": "#263142",
        "on-primary-fixed-variant": "#07497d",
        "tertiary": "#303436",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#b7bbbd",
        "inverse-primary": "#a0c9ff",
        "surface": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#8df2fc",
        "error-container": "#ffdad6",
        "surface-container-highest": "#d8e3fa",
        "surface-bright": "#f9f9ff",
        "surface-variant": "#d8e3fa",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#474b4d",
        "surface-tint": "#2d6197",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-secondary-container": "#006f77"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "2xl": "48px",
        "xl": "32px",
        "gutter": "24px",
        "3xl": "64px",
        "xs": "4px",
        "unit": "4px",
        "lg": "24px",
        "sm": "8px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "md": "16px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
